version: "3"

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=""
      - DB_NAME=bike_share
    command: go run main.go

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: bike_share
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      - URL=http://backend:8080/swagger/doc.json
